#!/usr/bin/env python
#-*- coding: iso-8859-1 -*-.
from random import choice
import time
print (" ______         _____  ")
print (" | ___ \       |  __ \ ")
print (" | |_/ /  ___  | |  \/ ")
print (" | ___ \ / _ \ | | __  ")
print (" | |_/ /| (_) || |_\ \ ")
print (" \____/  \___/  \____/ ")
print ("  ____  ____  ____  ____ ")
print (" ||T ||||D ||||L ||||G || ")
print (" ||__||||__||||__||||__|| ")
print (" |/__\||/__\||/__\||/__\| ") 
print ""
v = " 0.0.1"

print "GOOD dork gen" + (v)

real =raw_input("ingresa tu alias: ")
print("")
print "Hola Que Tal!! " + real + " encantado de conocerte :)"
time.sleep(3)
print("")
print(" GOOD-DORK GEN !!")
time.sleep(2)
print("")
print "bienvenido al generador, " + (real)
print ("")
dum =raw_input("ingresa tu dork: ")
print ("")
print "generando"

time.sleep(10)
print("")


print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)

print (choice(["trainers.php?id=", "play_old.php?id=","declaration_more.php?decl_id=","Pageid=","games.php?id=","newsDetail.php?id=","staff_id=","historialeer.php?num=","product-item.php?id=","news_view.php?id=","humor.php?id=","communique_detail.php?id=","sem.php3?id=","opinions.php?id=","spr.php?id=","pages.php?id=","chappies.php?id=","prod_detail.php?id=","viewphoto.php?id=","view.php?id=","view.php?id=","website.php?id=","hosting_info.php?id=","detail.php?ID=","publications.php?id=","Productinfo.php?id=","releases.php?id=","ray.php?id=","produit.php?id=","pop.php?id=","shopping.php?id=","productdetail.php?id=","post.php?id=","section.php?id=","theme.php?id=","page.php?id=","shredder-categories.php?id=","product_ranges_view.php?ID=","shop_category.php?id=","channel_id=",])) + (dum)
time.sleep(5)
#DEV BY:
#/********************************************\
#/                                            \
#/                                            \
#/              Emilio Barroso                \
#/                                            \
#/                                            \
#/********************************************\
